apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ANGq3cIzYqoNWslsTMZ9+gUt6YXog5W9kW3aIo/qDVcnPXEPRxo4xmbsWnupipUffWwauqRYt2QsaXWtsiTS32Mqvz5qVNJdTO40Mvs4G3yVgDFgzKmbZ6wTt6C9uQFpsOuzMWVLkAf+toEMfTW4xDBWef6ddSdLKrikk2DIq0SW77YvKaxPocEAK5HdCZ8vrFq+E+GqHtWTyoVuUaKqJleOznM6WyJMrBUkl2EpkyNWgM7iwGoYun81VyLVwYUaWGGMAwFTFz4bfW1jCWJ3L55l5tycIXS6wjCJdb3s/jST/FrPxIMp40TpGcE=,iv:n/kn92numi/5HlZiHq1TkPs4yHOb92KI7Awrllw0xKI=,tag:Q8o5JGnsl9aDE+vhrZKraw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1ppc8crvqj46l02zshwrmngfq6ykr9y9zlt7sty4nwamr08r3yefswufxlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdHRaamR5a2VGUnFPU3U3
            VkZqV2VBQ2xQMW9lM2FhYkk4YlJtaXptaUJNCjlRRWJtYVpVMW5NMU10UkhvUk9l
            NEhSTXgzU0k5cXJ2K1hSMEI0TUNWQVUKLS0tIFlod1N0MCtjM3NhdisxVUk1Ui9w
            ZEJiWk84YkszM0l5SVNDdTRVMnlnWFUKMpMCjBRjMb7h2W4ZbaTmAVrYeabthcrS
            vU6fmyzgY4IyylNneO89mYXoHz0f/dG8LbNggyR4NumDVCTQzg2pFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T14:12:39Z"
    mac: ENC[AES256_GCM,data:rS7FfGvkhjo5S7rAeJSMuAUgXjyTyrtiX0qvJaKSHi3RfydTCIUYpqDp7rKwWdi7p8VpxTWq8lX1mgEoAa2PgkXa2Ndyb8WqHFwpLstbrBOgOuaikjGmPuo4P++wNA1nBUp9RyEzgY3tH4Qox4+EirHcfQIMVYF9ksGUW0K93b0=,iv:jcJyqQggnYJo3p24pVnjR/ldFAW/Rb2+08F0aBtyDYY=,tag:G8SucZNm18cFPrRQorFsLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
