apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: shared-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2

  storage:
    storageClass: longhorn
    size: 10Gi

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  affinity:
    nodeSelector:
      workload.kubernetes.io/postgres: "true"

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-superuser

  monitoring:
    enablePodMonitor: true
