apiVersion: batch/v1
kind: Job
metadata:
  name: linkding-db-init
  namespace: shared-postgres
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: psql
        image: postgres:17.2
        command:
        - /bin/bash
        - -c
        - |
          export PGPASSWORD="$POSTGRES_PASSWORD"

          # Create user
          psql -h postgres-cluster-rw -U postgres -d postgres -c "
            DO \$\$
            BEGIN
              IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'linkding_user') THEN
                CREATE USER linkding_user WITH PASSWORD '$LINKDING_PASSWORD';
              END IF;
            END
            \$\$;
          "

          # Create database
          psql -h postgres-cluster-rw -U postgres -d postgres -c "
            SELECT 'CREATE DATABASE linkding OWNER linkding_user'
            WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'linkding')\gexec
          "

          # Grant privileges
          psql -h postgres-cluster-rw -U postgres -d linkding -c "
            GRANT ALL PRIVILEGES ON DATABASE linkding TO linkding_user;
            GRANT ALL PRIVILEGES ON SCHEMA public TO linkding_user;
          "

          echo "Database initialization complete!"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-superuser
              key: password
        - name: LINKDING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: linkding-db-app-user
              key: password
