apiVersion: apps/v1
kind: Deployment
metadata:
    name: cloudflared
    namespace: authentik
spec:
    selector:
        matchLabels:
            app: cloudflared
    replicas: 2
    template:
        metadata:
            labels:
                app: cloudflared
                policy-type: app
        spec:
            containers:
                - name: cloudflared
                  image: cloudflare/cloudflared:2026.1.2
                  args:
                    - tunnel
                    - --config
                    - /etc/cloudflared/config/config.yaml
                    - --protocol
                    - http2
                    - run
                  livenessProbe:
                    httpGet:
                        path: /ready
                        port: 2000
                    failureThreshold: 1
                    initialDelaySeconds: 10
                    periodSeconds: 10
                  ports:
                    - containerPort: 2000
                      name: http-metrics
                  volumeMounts:
                    - name: config
                      mountPath: /etc/cloudflared/config
                      readOnly: true
                    - name: creds
                      mountPath: /etc/cloudflared/creds
                      readOnly: true
            restartPolicy: Always
            volumes:
                - name: creds
                  secret:
                    secretName: cloudflare-tunnel
                - name: config
                  configMap:
                    name: cloudflared
                    items:
                        - key: config.yaml
                          path: config.yaml
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTFZhYW8rNllubHQ0TmFo
            b3d2ZTNGZmVLNEYybWFLRWMyeHRwRDFXOUVFCmVUK08zeTFSendmN3cva2t5Rzdh
            M3N4MHowaXhybW5RelAvRFNTUlhMK28KLS0tIG5RN3J2WUpBZkoxYndkdkQ5OTQv
            MTZCTjljMWpISWljRGNyVEFUQlRqTmMKQyEJgBBe12navguEIrCzc525P8KYscMK
            OJV4VinBTB18J0/k05ZA2PP43WZyYpx6l3O3KWTTPFY2g05KC7gW7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T10:46:03Z"
    mac: ENC[AES256_GCM,data:zrWWkq3/hQ/mHqOhn2zlLpR8WUxZMqtfwqETlZKudOn9w3W3TAUcS2USVORL/heahJGP9mZsSMLia2t1onaq2GdQATRSPSpYHBJCSL5J05DoRKfp71EPf4osVisenFWh+ZtR+zeDITC6jJHHB0jAhn42/FAjMk+qbEBufIUzffY=,iv:Qj3Oww+XqfGbe1dol9yeE/3t6Ohpx1eIcDpppNGUNRo=,tag:UVAiN1X+GyuGXV7YbI4FNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: cloudflared
    namespace: authentik
data:
    config.yaml: ENC[AES256_GCM,data:tTtO8a9KW2TPx8ZJ8cLeUMV/zXuTa7SPNWam62+b+JZBLt2kgf100zdbaTZeoDHjFlHm/tpoSFERET1dr/wcaAlD6OnvBXJQH+DM4/CLg67WpzUgOiw/PAAgXvb60QWxZ9k9oqGl5ozMUUSnrx8K8iZNEceJHnurmQkwe7/pOBbrPA1vRftuddh1CAIMj2dB+oZAB+c4c5fpTNjf391KQ3WPighyyZTv6yk3hu5aXM91t8+YoN9m7zlt9FGs/R9uBsOV12yu2+wCAkCKb18hMv3Ygdo25+d7ax7xc4Z9F4VMe1FQ8KAe5t9gLcczaFT1cZkdIE/Dh8iUFCbv0ckaWfsaq/ykeRerYWWMPYk8qX1NmFKyFUVEh1rWjJDH0CVuC/WveHYcI7uEsWuxdihe4cxu9la39bgeaoHL8Y2ahZMxaywKaMU0iUxMaS0PTxiWglnDzukQ5wM=,iv:gGm+LBTTf7dnN3uOTxt+jqmIRIeiMWsq+1nsU4PwNDU=,tag:uADxdNcbNVNjtip18ESUBA==,type:str]
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTFZhYW8rNllubHQ0TmFo
            b3d2ZTNGZmVLNEYybWFLRWMyeHRwRDFXOUVFCmVUK08zeTFSendmN3cva2t5Rzdh
            M3N4MHowaXhybW5RelAvRFNTUlhMK28KLS0tIG5RN3J2WUpBZkoxYndkdkQ5OTQv
            MTZCTjljMWpISWljRGNyVEFUQlRqTmMKQyEJgBBe12navguEIrCzc525P8KYscMK
            OJV4VinBTB18J0/k05ZA2PP43WZyYpx6l3O3KWTTPFY2g05KC7gW7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T10:46:03Z"
    mac: ENC[AES256_GCM,data:zrWWkq3/hQ/mHqOhn2zlLpR8WUxZMqtfwqETlZKudOn9w3W3TAUcS2USVORL/heahJGP9mZsSMLia2t1onaq2GdQATRSPSpYHBJCSL5J05DoRKfp71EPf4osVisenFWh+ZtR+zeDITC6jJHHB0jAhn42/FAjMk+qbEBufIUzffY=,iv:Qj3Oww+XqfGbe1dol9yeE/3t6Ohpx1eIcDpppNGUNRo=,tag:UVAiN1X+GyuGXV7YbI4FNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: authentik
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:JE6JX3GVx/74WO47EQRh4Y+mNRUMrJVL1YU9BHzULdipKRJ/v8zuA3+DWoXNxukL/oIgLxDErPjM79JXVyirbah3gVLGpAF4UBhqYV6p3bb5wsHdX+eAjZYJKLxVOfzQtMuDMVz8TwkZ0hAt3ONuk57FuJ5QB0QJbhOLdzEV5M9CuL4p9GH3cgFxbfdPzskjpcGYh5W3UGH1vXfYQOWruVqaWhlie+U72GKl5pVSTfM=,iv:T3Xyt5w6cHqcAbXH4H1uVp30MlM1On6E2SwZXFgc9Q8=,tag:Ya4kJxqql1oDtTIc6tKmDw==,type:str]
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTFZhYW8rNllubHQ0TmFo
            b3d2ZTNGZmVLNEYybWFLRWMyeHRwRDFXOUVFCmVUK08zeTFSendmN3cva2t5Rzdh
            M3N4MHowaXhybW5RelAvRFNTUlhMK28KLS0tIG5RN3J2WUpBZkoxYndkdkQ5OTQv
            MTZCTjljMWpISWljRGNyVEFUQlRqTmMKQyEJgBBe12navguEIrCzc525P8KYscMK
            OJV4VinBTB18J0/k05ZA2PP43WZyYpx6l3O3KWTTPFY2g05KC7gW7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T10:46:03Z"
    mac: ENC[AES256_GCM,data:zrWWkq3/hQ/mHqOhn2zlLpR8WUxZMqtfwqETlZKudOn9w3W3TAUcS2USVORL/heahJGP9mZsSMLia2t1onaq2GdQATRSPSpYHBJCSL5J05DoRKfp71EPf4osVisenFWh+ZtR+zeDITC6jJHHB0jAhn42/FAjMk+qbEBufIUzffY=,iv:Qj3Oww+XqfGbe1dol9yeE/3t6Ohpx1eIcDpppNGUNRo=,tag:UVAiN1X+GyuGXV7YbI4FNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
