apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: 1.7.2
  targetNamespace: longhorn-system
  install:
    createNamespace: false
  values:
    defaultSettings:
      defaultReplicaCount: 1
    persistence:
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain
