apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot
  namespace: longhorn-system
spec:
  name: snapshot
  cron: "0 3 * * *"
  task: snapshot
  retain: 7
  concurrency: 2
  labels:
    type: snapshot
