apiVersion: v1
kind: Secret
metadata:
    name: authentik-outpost-token
    namespace: pgadmin
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:bYQM7pjqYk6tIAB33i1rnXTmUR44PJSg/1Y1ym931YP5x5rwtRdFk6FI7+qmpZWG2sM4R73Id9jKVg5J,iv:YP6yPm55HMCTK95VjIBBxovjxUSiZSJJ0raVw4FJRCM=,tag:tY80PpI66+UYcP7TfNxSXQ==,type:str]
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRkxuUnhLcEJxY3o0RXdX
            cWc5WGhYOXVyN1pjV0dUcFN3eUswVGx4RUdzClZzRU94M0NQWlhKVUFEeklTWXdX
            VkRvOEt5enB2OEQxV2ZFUFlRQVJ2emMKLS0tIEVmRjlLU0xETHJtY1VlYjBsYUxT
            ZmtzYmZKbFNtUXp5R2NYVjRkZmVwUlEK95qzAvIOBOpixNmKr/b6mC9OrmMLr53r
            CJ8qABdW9vaqq6kaZ5TOzf5bDQRXbp7C/UU3NeohjUpM3LTM10prWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T11:41:27Z"
    mac: ENC[AES256_GCM,data:JZ/wINAtgTPZbD7ApzLwZyYWXqhDCIujEuKU57sLxSYXamGpmhlR4fLnKjift70p/32GnMRvvPZApW0PmZlXTW3BBpvGVuW7I6EP9ahJ9X/dS1vmOtXBx38wAbGv/EwvFt3DpI2BJEAGYhk8U61ci47KGglJGrgnfUiKoj5lNKk=,iv://0F8KS2n85OZQPjxddCHjPb5/oip0OKeOecxzS3+TE=,tag:M23HjdSo7tnSY7ocSCoo9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: authentik-outpost-pgadmin
    namespace: pgadmin
    labels:
        app: authentik-outpost-pgadmin
        app.kubernetes.io/name: authentik-outpost-pgadmin
        app.kubernetes.io/instance: pgadmin
        app.kubernetes.io/component: proxy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: authentik-outpost-pgadmin
    template:
        metadata:
            labels:
                app: authentik-outpost-pgadmin
                app.kubernetes.io/name: authentik-outpost-pgadmin
                app.kubernetes.io/instance: pgadmin
                app.kubernetes.io/component: proxy
                policy-type: app
        spec:
            containers:
                - name: outpost
                  image: ghcr.io/goauthentik/proxy:2025.10.3
                  env:
                    - name: AUTHENTIK_HOST
                      value: https://auth.simeonivanov.org
                    - name: AUTHENTIK_INSECURE
                      value: "false"
                    - name: AUTHENTIK_TOKEN
                      valueFrom:
                        secretKeyRef:
                            name: authentik-outpost-token
                            key: token
                  volumeMounts:
                    - name: sessions
                      mountPath: /dev/shm
                  ports:
                    - name: http
                      containerPort: 9000
                      protocol: TCP
                    - name: https
                      containerPort: 9443
                      protocol: TCP
                    - name: metrics
                      containerPort: 9300
                      protocol: TCP
                  livenessProbe:
                    httpGet:
                        path: /outpost.goauthentik.io/ping
                        port: http
                    initialDelaySeconds: 30
                    periodSeconds: 30
                  readinessProbe:
                    httpGet:
                        path: /outpost.goauthentik.io/ping
                        port: http
                    initialDelaySeconds: 10
                    periodSeconds: 10
                  resources:
                    limits:
                        memory: 512Mi
                    requests:
                        cpu: 50m
                        memory: 128Mi
            volumes:
                - name: sessions
                  emptyDir:
                    medium: Memory
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRkxuUnhLcEJxY3o0RXdX
            cWc5WGhYOXVyN1pjV0dUcFN3eUswVGx4RUdzClZzRU94M0NQWlhKVUFEeklTWXdX
            VkRvOEt5enB2OEQxV2ZFUFlRQVJ2emMKLS0tIEVmRjlLU0xETHJtY1VlYjBsYUxT
            ZmtzYmZKbFNtUXp5R2NYVjRkZmVwUlEK95qzAvIOBOpixNmKr/b6mC9OrmMLr53r
            CJ8qABdW9vaqq6kaZ5TOzf5bDQRXbp7C/UU3NeohjUpM3LTM10prWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T11:41:27Z"
    mac: ENC[AES256_GCM,data:JZ/wINAtgTPZbD7ApzLwZyYWXqhDCIujEuKU57sLxSYXamGpmhlR4fLnKjift70p/32GnMRvvPZApW0PmZlXTW3BBpvGVuW7I6EP9ahJ9X/dS1vmOtXBx38wAbGv/EwvFt3DpI2BJEAGYhk8U61ci47KGglJGrgnfUiKoj5lNKk=,iv://0F8KS2n85OZQPjxddCHjPb5/oip0OKeOecxzS3+TE=,tag:M23HjdSo7tnSY7ocSCoo9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Service
metadata:
    name: authentik-outpost-pgadmin
    namespace: pgadmin
    labels:
        app: authentik-outpost-pgadmin
        app.kubernetes.io/name: authentik-outpost-pgadmin
        app.kubernetes.io/instance: pgadmin
        app.kubernetes.io/component: proxy
spec:
    selector:
        app: authentik-outpost-pgadmin
    sessionAffinity: ClientIP
    sessionAffinityConfig:
        clientIP:
            timeoutSeconds: 10800
    ports:
        - name: http
          port: 9000
          targetPort: http
          protocol: TCP
        - name: https
          port: 9443
          targetPort: https
          protocol: TCP
        - name: metrics
          port: 9300
          targetPort: metrics
          protocol: TCP
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRkxuUnhLcEJxY3o0RXdX
            cWc5WGhYOXVyN1pjV0dUcFN3eUswVGx4RUdzClZzRU94M0NQWlhKVUFEeklTWXdX
            VkRvOEt5enB2OEQxV2ZFUFlRQVJ2emMKLS0tIEVmRjlLU0xETHJtY1VlYjBsYUxT
            ZmtzYmZKbFNtUXp5R2NYVjRkZmVwUlEK95qzAvIOBOpixNmKr/b6mC9OrmMLr53r
            CJ8qABdW9vaqq6kaZ5TOzf5bDQRXbp7C/UU3NeohjUpM3LTM10prWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T11:41:27Z"
    mac: ENC[AES256_GCM,data:JZ/wINAtgTPZbD7ApzLwZyYWXqhDCIujEuKU57sLxSYXamGpmhlR4fLnKjift70p/32GnMRvvPZApW0PmZlXTW3BBpvGVuW7I6EP9ahJ9X/dS1vmOtXBx38wAbGv/EwvFt3DpI2BJEAGYhk8U61ci47KGglJGrgnfUiKoj5lNKk=,iv://0F8KS2n85OZQPjxddCHjPb5/oip0OKeOecxzS3+TE=,tag:M23HjdSo7tnSY7ocSCoo9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
