apiVersion: v1
kind: Secret
metadata:
    name: linkding-database
    namespace: linkding
type: Opaque
stringData:
    LD_DB_ENGINE: ENC[AES256_GCM,data:LhOePpnEsxU=,iv:e6VK02sVPK+6xko/Aacks/NBOJCPlKZZc+2ig0a/R3I=,tag:qRAgbSMOiwlF1YtwmTkxgg==,type:str]
    LD_DB_DATABASE: ENC[AES256_GCM,data:ibT6+nWNhu4=,iv:f2EE5xv9INtKvf3UO0GGrcL8IbMiRKAlpsagIGFeM2A=,tag:EBFFh96OCmTWGblfQ3G0hQ==,type:str]
    LD_DB_USER: ENC[AES256_GCM,data:cP2M6kXCva4OkYxRDA==,iv:KwCxDar290q5aL9hn4qMVQwKAiHuMhotDudyqHBi7i8=,tag:z1vEymeEQcULadIypXgbqQ==,type:str]
    LD_DB_PASSWORD: ENC[AES256_GCM,data:mB+cWX00k5v+qNWzwb2x2A==,iv:isN5G+rgIUsGu7uMx5qvJQuM1se6h9RhsOtcr5dCp5Q=,tag:QKakbb4NHGmgHrn8aE6G5w==,type:str]
    LD_DB_HOST: ENC[AES256_GCM,data:lZGDkzooaog5Mcj0s+apEOMKwvLUEjyTGRLQBBH3n31NDPbAOwx5O2oHx6IRDR+2W8Cb/r0=,iv:ScZLpCzrWmpM8ExSWwKmptI4S7HNvYDGcUb9XMUgaNY=,tag:iQR5UzqCjavw4trU10QRIQ==,type:str]
    LD_DB_PORT: ENC[AES256_GCM,data:3hh0Sg==,iv:vDiBKT4U47WLhHYKDMyvted5LiEel43MFgKX9W+ajzk=,tag:gfCcbhbq+4uLhh4aXuxCrw==,type:str]
sops:
    age:
        - recipient: age1ppc8crvqj46l02zshwrmngfq6ykr9y9zlt7sty4nwamr08r3yefswufxlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVWIyam9CMjQwUjFuTlFW
            VTJLeVkvbG83cHoyOUFkKzh5WkxQSXdkenpRCkVuVDZzTytONkpyakszMnZsaUU5
            KzRxTTl3enBScGd3SDBLenRSeTVndVEKLS0tIFFybWhObldrQy8zK0FHdFRuMnJi
            SHlTNEV2S1pkY1BHUE1LK05MWWJuam8KsuD3y6E8JLUwWEWVzBoGwGz6FDqYaJZb
            TBKvGL+UrviMUfceIYBvjNp+/6QRIOdTYPIZV8waSkcTqpRcVHyy/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T19:18:15Z"
    mac: ENC[AES256_GCM,data:0Qpl++AstVWOVzyGeM2sDZThkf++G1IfvxeTilOrfGsO7iMKzq7JH4gKhfAsdvUdOKVSGvfkbZhv+wCeSIk5pjI36BGPILiROW1cRLEjlwZ8wtifGxcqKUaiGMFfUD4DV1Pr3Q/q2Mz0TRPjT02HbeikhzWUooiPjVmCTnv73mI=,iv:f0NOyMZgGMCiZQ13/f1KWTdWqUBs8VkOpRwK5kDwsKk=,tag:k8bYyM3aZuZPc/JX4srXLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
