apiVersion: v1
data:
    password: ENC[AES256_GCM,data:cGKq+/FKQLM=,iv:I34Fu4LYHv6Q9sFMM+6iZdcg1pSN7gXXHh43LrHD2Og=,tag:Ag4dIlK1t9mm+w9/t+l4ng==,type:str]
    user: ENC[AES256_GCM,data:lIxfODygfEs=,iv:hy763S7CXuMCy6IEyWMXakAf60LbghZghzEjVE9LXFw=,tag:qCudDLPABKvrCasz2ojVNQ==,type:str]
kind: Secret
metadata:
    name: secret
sops:
    age:
        - recipient: age1ppc8crvqj46l02zshwrmngfq6ykr9y9zlt7sty4nwamr08r3yefswufxlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVERyTFVTSVI0TmhrSGxG
            RnloTXUzZ1RuVjkyY3lXOHVDSzJpMitYSzNJCk90aDloSGlnQUVwSXBVTzhGakFs
            VDFQN0srVHdnbi9mdGdVSlk0S0MyMjQKLS0tIHE4T3EzNnowQkFkZnI2d0x3MVBz
            SHZaVUxDb3Z0T3J5TDBLbjBpdWFTakkKxxtlpLxXN3C2G02MK0BlGozkmBjyRptJ
            j9KcuPxm2sXb5Erq1CWwTkZk71Ny/SkDiLjMDN4KCdcodgFES+Ng1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T10:00:19Z"
    mac: ENC[AES256_GCM,data:i+/Xut8e8+46ROxIzRTHJb70IShGQqP7VCRtAtN5MV6Ylm8ebBn0GPwQ5w7Ml6+U0GabYGzsD12YudbZ98nVjSK57SeJQs9REygvg9a23sDE5cvGaI+FGMRQqcZU+a34cP+85juSjL6sLY9+Ldw7utmXgLxV41VwioVR2b6piIs=,iv:cc7BeruLOIQTYaAej7PKoqaq9POWC8swFWuCgUYXUfY=,tag:yYY/GoPEApcpFwZrVvL/RQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
