apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
  namespace: linkding
  annotations:
    recurring-job.longhorn.io/source: |
      [
        {"name":"linkding-nightly-snapshot","isGroup":false}
      ]
