apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-db-creds
    namespace: pgadmin
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:L3uhhnsMxA==,iv:yvQsTiMpHAMvM+AiZyeXeADpZvrPP55K/RPkM1ynCLA=,tag:NNwKdKtXTxvNNQwRf+NycQ==,type:str]
    password: ENC[AES256_GCM,data:HBMiN6wr04yKobKudO6kJPmBpJ48HAQAnX7mjvWE8h+bIsLESdozJCiAD8I=,iv:XIGDyZzPdie+2ykoySgnirSBG9okTI18NeOjCCLZOHo=,tag:oqDPt3tRpFOsvEgvgseG+A==,type:str]
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNlNNc0Z2bzVadHlDRDYv
            bXpmc2ZMNEMvcTBsdzVsU1FvOEc2QTdEUW1nCkphckQ2ODBjeUJacHlZcnJUTWIz
            Y3JNZ3N2L21yVk9MVkRiYVd1MHZQOTQKLS0tIGZDR0o2c2FoTngyOGdMNE96NEtn
            dmlIZ1J1c2hpV29KUkREdElrZTBYQzQK4+j/6YvKlMXvsCvx85vV/7QC6zxPnt2m
            rfPPu99AgdEnXEEgcVpl/IxMMzqCdggbTilbeBernP25IF7AatWjCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T10:46:03Z"
    mac: ENC[AES256_GCM,data:AqJKvZSUhbirR/3TDU29C3W6OxhNqbpR7V2lj3jKMe8MNNq7Z5W/WAD/fB67fYUPxyBYxESJkAmrI2Hxg9EBo03pX2MJc/QFPAiFlkWXrwamLKBPPULvLC0xe6LkWE52zm48ch3Z1Ib0Q6Ps77yaQdJ09IuL9f+OG0PUnPFvA8w=,iv:9l5DOjJ9upI9nwYQfpfM4e1I9dqJrlevEavQjAJxix8=,tag:6Tg0jLhoVrhqXtS73/F2HQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
