apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-container-env
    namespace: pgadmin
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:EUrhZJicnLqqjan5IoJaqCMhdaJwD/E=,iv:wysuU3t4gCu7vah1mRNcL3IztYhonlDVp5CBIPe0aoc=,tag:/KFM9gxAb1IKTwZCI2YeKg==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:VQzf3kem9lk81Q30G2YzNYumTWXoK+YvWS2JgSwOJJMEx0MEpEAxBWfm0Ec=,iv:+RI0+021ncXflQfGFFpDegIFjVz/3VxUUFtX6OnLb3k=,tag:UIUGaQ5d8DdPrXerXtNiXg==,type:str]
    PGADMIN_SETUP_EMAIL: ENC[AES256_GCM,data:gOwtMLpa3wIWjgu4uF5Q/ZjJ44euO/Q=,iv:OGPIXQSA4WrpuVJ/VXcQuAkwr3MpjsZTvBu7fHpOtq0=,tag:nSDcNl65BtRIubQSCVLLwg==,type:str]
    PGADMIN_SETUP_PASSWORD: ENC[AES256_GCM,data:ygmNYHG/C9BoxbYP3AcDiY688pxDs8NY+8bg/x0UNGxErkn+lsUlJHH4Iyg=,iv:TI8+NHDTa0M2vGA3mVTW3grzjAou0g2rnffUQkLZe5I=,tag:ywbcGZqoJVPqA2l9kdIDsw==,type:str]
    PGADMIN_CONFIG_CONFIG_DATABASE_URI: ENC[AES256_GCM,data:H3Blged0bT3EYcnngtc8GFWNDtM4FutpM4YOK5swX3j5oBxkvkHWSfmvhANXIYTYh1xoD4aP1KxdoFVnFYexxowmCWNOCDIJUO7DcVxXThvvaeBZiph1JcZAgRthcO0Ro8KR++FG4FphuwByXqbUY/Cn6PEsRnxgCgk=,iv:0vpiI1rpvgMfst8ji0RaICEODyi88mUMAwwwZN08ag4=,tag:kzxS3EVt93pS2SPIuFdyuQ==,type:str]
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL3MxdWF5LzJBSkEvRk9M
            K2FIOUNQUXoyZUV6aHZOdmc5UVhVQ3ZTdEVZCmlHN0U5M0FjejhFOEhOajB5Q0M2
            b1NwTGhKWEZSOFhDS2x0cjdTUElYWGMKLS0tIHpGaWJ2SmxzN0NNRnF0cXRxcGtE
            R3cyZ2c4emJsSkhJd253aHNXQ3FlSUkKMsnCEfm5rU3EiF4IM2q4g6j7IpC2DzBX
            6z+z+wpRXwJBSmk18j6/5YsbtASLwthRIAUT2rjnPcDdsDYuYBD4ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T10:46:03Z"
    mac: ENC[AES256_GCM,data:O64mHxtWRofv+UneKJ1baFvAriuZrh0wS/S0hlAKwMHY/cFPvDSbD+7S9xwDJtvc8niThnW7M8YDxloA/dtory2KQQbUekqstzzb6ifIqFQgV+UmAMok0zN1nbmNhDFUokpnKOaCcyuyuR6DcgDAUE3BwFtw635cOr/IMnIU/Ew=,iv:IOdLLn7MtCUza54gNj2EjuqT4gcwAzGk5+SCxbVdo3A=,tag:pSJTd+K5VKPkqUarsNh3Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-pgpass
    namespace: pgadmin
type: Opaque
stringData:
    pgpass: ENC[AES256_GCM,data:fCaxm1z/Jyl3B2IUZgIdCgcMeUQlQHMVVrlOpwC57O72c9ZKNGUtwLnKD+Lm9uc+M9cz9TPa7UaL1G1Ik7lq/dO3jGgOelnPW6Rpj4gG6IouMcvUlFK2U+nkiv8OH4CT9uu3R9QxzthL8LgDiUgkNhSa0ub/xHc3k8vE8/1kdaQQmQUlxidGY4kGvaBrznuBEnRv0q+xZ0EsJ6wKX1jrK1jpdcyOjSGsSdaqvFEUvouX5S+kskuBJira+B0KGI4E92yode2FcY+NzkrLLmA=,iv:L4Xb/QfFdnqoK6y0oY0kBpBqB29UPrGPCEec20sQNvQ=,tag:Bp6ea253S2G9jxZdbaiNsQ==,type:str]
sops:
    age:
        - recipient: age1uwpe4cgfkhrx8k0kzflv2sneyfqpvdegz3p4lsn0e0nxazxegqwszyz2e0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL3MxdWF5LzJBSkEvRk9M
            K2FIOUNQUXoyZUV6aHZOdmc5UVhVQ3ZTdEVZCmlHN0U5M0FjejhFOEhOajB5Q0M2
            b1NwTGhKWEZSOFhDS2x0cjdTUElYWGMKLS0tIHpGaWJ2SmxzN0NNRnF0cXRxcGtE
            R3cyZ2c4emJsSkhJd253aHNXQ3FlSUkKMsnCEfm5rU3EiF4IM2q4g6j7IpC2DzBX
            6z+z+wpRXwJBSmk18j6/5YsbtASLwthRIAUT2rjnPcDdsDYuYBD4ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T10:46:03Z"
    mac: ENC[AES256_GCM,data:O64mHxtWRofv+UneKJ1baFvAriuZrh0wS/S0hlAKwMHY/cFPvDSbD+7S9xwDJtvc8niThnW7M8YDxloA/dtory2KQQbUekqstzzb6ifIqFQgV+UmAMok0zN1nbmNhDFUokpnKOaCcyuyuR6DcgDAUE3BwFtw635cOr/IMnIU/Ew=,iv:IOdLLn7MtCUza54gNj2EjuqT4gcwAzGk5+SCxbVdo3A=,tag:pSJTd+K5VKPkqUarsNh3Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
