apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
  annotations:
    recurring-job.longhorn.io/source: '[{"name":"linkding-nightly-snapshot","isGroup":false}]'
    longhorn.io/disk-selector: "storage"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
