apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:oPfmMZa5sBQ4jlPSJQ1G1hUR/OO9R7PcdOCZ/W71fX0C9tpascLdmjjBZUpC1OpWuHbZqo9PyAo=,iv:JGzc/BrB7rrvzx98lD8V1ahfFX7qLkEAOizmgPWkLpQ=,tag:bmEmAaql13m1RCaIhfIgvQ==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1ppc8crvqj46l02zshwrmngfq6ykr9y9zlt7sty4nwamr08r3yefswufxlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqalNTc2Vsd3RpRFRudDBC
            bFgwR1JnZFgwQkZFVXljZnNuOFpoUmVyUDJNCjlOZU9JSmNtcitjY04reHI2YVk0
            V0RpR3RNdUNMMjRQQWV6a0U0OW5sTVUKLS0tIHp4VFd0YzdlZHJXSjRGTEpGNTd6
            aWJXazhFYjRUWWh6Yk02M2h6SDVNa2MKUtWMu2xtKvDG2uKD257+6O/CvkD8Owt5
            mrzhR69e1Ejx+HP7ssklEjmd4/hAerK81aD3VJ93dvKocXrYl081Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T11:38:19Z"
    mac: ENC[AES256_GCM,data:5IZVqYcVutLpdn5tyG/3K4nSPUk0dkXKl4RhR3RtrDlojbCazG1gE/NSLouBAhzBkk3hY6U62e7Vj87IbPG5yfI7imXyYBYlt4e0nWGmHwnmaxH0UGRQCXW21J/mYsCAi0t08yYWBDotuu3iYYoJiZ31pXTeoZT+8rc7EqoRl7E=,iv:5zQmGWJE6Xu1FoQv1zzosq8/j8reWujhQ7UvrWWdI/k=,tag:3ZVhd/YiUteFAcPM0wc72A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
